import type { Metadata } from "next";
import "./globals.css";
import { Header} from '@/components/index'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-[100%]">
      <body className="h-[100%]">
        <div className="flex flex-col h-[100%]">
          <Header/>
          <main className="flex-[100%] flex-grow">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
